# Read the Docs configuration file for Noisemaker
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build formats (PDF, ePub, etc.)
formats:
  - pdf
  - epub

# Python configuration
python:
  install:
    - requirements: docs/sphinx-requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "20"
  jobs:
    post_checkout:
      # Ensure the docs directory is accessible
      - ls -la docs/
    post_install:
      # Verify Python installation
      - python --version
      - pip list | grep noisemaker
      # Install Node.js dependencies and build bundle
      - npm --version
      - node --version
      - npm install
      - npm run bundle
      # Copy bundle to docs static directory
      - cp dist/noisemaker.min.js docs/_static/
      - ls -lh docs/_static/noisemaker.min.js
