#!/bin/zsh

set -e

if [[ $# -gt 0 ]]; then
	if [[ $1 == "all" || $1 == "ALL" ]]; then
		unset EFFECT_ONLY
	else
		EFFECT_ONLY="${(j:,:)argv}"
	fi
else
	EFFECT_ONLY="nd/physarum"
fi

if [[ -n ${EFFECT_ONLY-} ]]; then
	EFFECT_ONLY="$EFFECT_ONLY" npx playwright test --headed --reporter=line tests/playwright/effects.spec.js
else
	npx playwright test --headed --reporter=line tests/playwright/effects.spec.js
fi
